### PR TITLE
Speed up processing large amounts of bisect output

### PR DESCRIPTION
**Pull request by edwintorok**
Previously bisect-summary would hold all bisect*.out files passed on the command-line in memory, growing to >10GiB of memory, and it was also processing more information than required due to using a deprecated API.
Fusing `List.map` and `List.fold_left` avoids the high memory usage, and switching to the new API avoids processing the 'points' when we only care about the 'counts'.

With all these changes it now takes seconds to process the results instead of minutes.

There is still a problem with exceeding the maximum length of command-line arguments when trying to pass everything in one call (worked around by renaming to shorter names), but that is a topic of another PR to optionally read the filenames from stdin instead of argv.

### CODE REVIEW

**Comment by lindig** [comment]
Could you rebase? I will merge the change after that. The project moved to Dune and I should make a new Opam release.

**Comment by edwintorok** [comment]
Hmm I get 'Unbound module Bisect.Common', maybe my version of bisect_ppx is wrong though (and `dune build` does nothing, I think we need a `public_name` in the dune file otherwise it builds nothing unless I explicitly do a dune build/exec of src/summary).

**Comment by edwintorok** [comment]
I've updated the PR to fix the build with bisect_ppx 2.6.0. Unfortunately bisect_ppx 2.7.0 removes the API that we rely on here (but we still use 2.6.0 in xs-opam, so should be fine for now).

**Review by lindig — APPROVED** [review]
Great! Thank you.
